### PR TITLE
Fix conveyor belt velocity

### PR DESCRIPTION
**Pull request by notgoodusename**
[video demonstration](https://streamable.com/bubsi4)
also ramps are weird because the abs velocity isnt correct (instead of -300, u get something like -276~), you could try rounding it but i dont think it makes that big a difference

### CODE REVIEW

**Comment by emilyinure** [comment]
the dilemma with the conveyor belts is that the direction isnt networked, only the speed, im considering doing some type of caching based on the entity the player is touching along with velocity changes. unsure about it though

lgtm otherwise, i am going to change a couple things and push it tomorrow

**Comment by notgoodusename** [comment]
Fixed jittering when melee is out

**Comment by notgoodusename** [comment]
setCollisionBounds does the [scaling](https://github.com/lua9520/source-engine-2018-hl2_src/blob/master/game/shared/collisionproperty.cpp#L674-L675)

**Comment by notgoodusename** [comment]
I thought about the movedir not being networked, i guess you could technically do something like decompiling the map and read the moveDir directly, but that would mean a lot of work

**Pull request merged**
